buildscript {
    ext {
        repos = {
            gradlePluginPortal()
            mavenCentral()
        }
        springBootVersion = '3.5.16'
        springCloudVersion = '2025.0.3'
        lombokVersion = '1.18.30'
        vauntVersion = '1.0.28'
        springdocVersion = '2.8.17'
        requestValidatorPactVersion = '2.22.0'
        postgresVersion = '42.4.0'
        httpClientVersion = '4.5.14'
        consulApiVersion = '1.4.5'
        coverallsVersion = '2.12.2'
        grgitVersion = '5.3.3'
    }
}

plugins {
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'com.github.kt3k.coveralls' version "${coverallsVersion}"
    id 'org.ajoberstar.grgit' version "${grgitVersion}"
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'idea'
    apply plugin: 'jacoco'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    repositories(repos)

    group = 'com.hltech.judged'
    version = buildVersion()

    jacoco {
        toolVersion = "0.8.11"
    }
}

subprojects {
    apply plugin: 'groovy'
    apply plugin: 'application'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'

    apply from: '../gradle/test.gradle'

    jar {
        enabled = false
    }
}

bootJar {
    enabled = false
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

coveralls {
    sourceDirs = subprojects.sourceSets.main.allSource.srcDirs.flatten()
    jacocoReportPath = "${layout.buildDirectory.get()}/reports/jacoco/codeCoverageReport/codeCoverageReport.xml"
}

task codeCoverageReport(type: JacocoReport) {
    executionData fileTree(project.rootDir.absolutePath).include("**/build/jacoco/*.exec")

    subprojects.each {
        sourceSets it.sourceSets.main
    }

    reports {
        xml.required = true
        html.required = true
        csv.required = false
    }
}

codeCoverageReport.dependsOn {
    subprojects*.test
}

def buildVersion() {
    def baseVersion = 1

    def commitsCount = grgit.log().size()
    def lastCommit = grgit.head().abbreviatedId
    return "${baseVersion}.${commitsCount}.0_${lastCommit}"
}
