on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            -
              name: Set up JDK 11
              uses: actions/setup-java@v2
              with:
                  java-version: '11'
                  distribution: 'adopt'
            -
              name: Cache Maven packages
              uses: actions/cache@v2
              with:
                  path: ~/.m2
                  key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-m2
            -
              name: build with maven & generate reports
              run: mvn clean verify jacoco:report coveralls:report
            -
              name: build docker images for server and agent
              if: contains(github.ref, "master") && github.event_name != 'pull_request'
              run: mvn validate docker:build@build-docker -P docker-app -f ./judge-d-server/pom.xml
            -
              name: push to docker registry
              if: contains(github.ref, "master") && github.event_name != 'pull_request'
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: hltech/judge-d
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            -
              name: push to heroku registry
              if: contains(github.ref, "master") && github.event_name != 'pull_request'
              uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: "YOUR APP's NAME"
                  heroku_email: "YOUR EMAIL"





