version: '3.7'

services:
  judge-d:
    image: hltech/judge-d
    ports:
      - 8080:8080
    environment:
      - DB_CONNECTION_STRING=jdbc:postgresql://postgres:5432/judge_d
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DRIVER_CLASS=org.postgresql.Driver
      - PACT_BROKER_URL=http://some-host/
      - PORT=8080
    external_links:
      - postgres
